version: '3.9'
services:
  rabbitmq3:
    container_name: Rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    volumes: 
      - ./db-data:/var/lib/rabbitmq
      - ./conf:/etc/rabbitmq
    ports: 
      - 15672:15672
      - 5672:5672

  emailsendingworkerservice:
    restart: "no"
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    links:
      - "rabbitmq3:rabbit"

  storedemailstatusupdateworker:
    restart: "no"
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    links:
      - "rabbitmq3:rabbit"

  documentforemailpreparingworker:
    restart: "no"
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    links:
      - "rabbitmq3:rabbit"