name: automerge

on:
  push:
    branches:
      - 'master'

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Merge
      uses: robotology/gh-action-nightly-merge@v1.3.3
      with:
        stable_branch: 'master'
        development_branch: 'develop'
        allow_ff: false
        user_name: 'Automerge'
        user_email: 'vodovoz.pril@gmail.com'
        push_token: 'VODOVOZ_TOKEN'
      env:
        VODOVOZ_TOKEN: ${{ secrets.VODOVOZ_ACTIONS }} 
